### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by abubakar-iqbal** [ssovit/TikTok-API-PHP#10]
I just checked that, the API has not returned the user data by calling the function 

` $api = new \Sovit\TikTok\Api();
        $account = $api->getUser($username);`
        
 Could you please confirm it?

**Comment by PeterJason** [comment]
I think the TikTok changed the code.

**Comment by PeterJason** [comment]
The code was updated, but the followers are rounded.

**Comment by abubakar-iqbal** [comment]
> I think the TikTok changed the code.

Yes, I checked with other API they also facing the same issue.

Do you find any other solution to it.?
