### ISSUE TITLE
Temporary Empty Responses

### ISSUE THREAD

**Issue by Offek** [ssovit/TikTok-API-PHP#12]
Hi,

First of all thank you for such a great library.
I've noticed that sometimes the API functions will return nothing for a period of time, literally empty arrays. Stream would not work either.
After some time, the same functions would return the correct results without any changes done on my side.
I tested with multiple IPs, worked with and without proxies and the issue still occurs.
I was wondering what could be the cause of this issue, and how could we possibly debug and look into a fix?

Thanks in advance!

**Comment by ssovit** [comment]
Sounds like you are making lots of requests in short interval from same IP and you are getting banned/captcha. I suggest you get rotating proxy service.

**Comment by Offek** [comment]
Hi, as I mentioned, I’m using a rotating proxy. I tried with 250 different ones. I can continue to investigate.
