### ISSUE TITLE
HTTP request failed! HTTP/1.0 403 Forbidden

### ISSUE THREAD

**Issue by truejay** [ssovit/TikTok-API-PHP#20]
https://v16-web.tiktok.com/video/tos/alisg/tos-alisg-pve-0037c001/7a0c123fa06749418b99fbb96943deea/?a=1988&amp;br=2434&amp;bt=1217&amp;cd=0%7C0%7C1&amp;cr=0&amp;cs=0&amp;cv=1&amp;dr=0&amp;ds=3&amp;er=&amp;expire=1611651989&amp;l=202101260306220101880612151E3009AF&amp;lr=tiktok_m&amp;mime_type=video_mp4&amp;pl=0&amp;policy=2&amp;qs=0&amp;rc=andpO215ZXRyeDMzOjczM0ApZTk3ZmRlOGVkNzQ5PDNkOGdlMW9yZ2xlamZfLS1jMTRzczJiNC41YzNjMjIwXjQtMTM6Yw%3D%3D&amp;signature=4b3f487d48cdb8ca6d3a0db7ccb54406&amp;tk=tt_webid_v2&amp;vl=&amp;vr=): failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden

**Comment by ssovit** [comment]
You cannot request video urls without proper http headers.

See [video stream example](/ssovit/TikTok-API-PHP/blob/master/example/stream-video.php)
