### ISSUE TITLE
can't load more videos from user or challenge

### ISSUE THREAD

**Issue by anaouda** [ssovit/TikTok-API-PHP#25]
hello sir, 
thank you for your amazing project
i tried to get user feed or challenge feed but i got only 28 video, how to get the next videos or how to get all videos of user or challenge
can you help me please 
thanks in advance

**Comment by ssovit** [comment]
Amount of videos per page depends on popularity of user/challenge/music. More popular channel gives more result per page. 

For next page set of results, you need to use value from `maxCursor` object which you get on current page request. By default, `maxCursor` is set to `0` for the first page.

like you can use `$userFeed=$instance->getChallengeFeed('bushit',30);` where `maxCursor=30` and for the next page, you get maxCursor value in that JSON result.

**Comment by anaouda** [comment]
thanks for your help
