### ISSUE TITLE
getMusic fix

### ISSUE THREAD

**Issue by cr1gger** [ssovit/TikTok-API-PHP#27]
Don't work... It seems tiktok closed this method, urgently needs to be repaired!
Previously worked, today stopped, always returns false

**Comment by ssovit** [comment]
Just tested, seems to be working fine on my end. Try using proxy.

**Comment by cr1gger** [comment]
> Только что протестировал, похоже, с моей стороны все работает нормально. Попробуйте использовать прокси.

Here is the response from the tiktok server: 
 `object(stdClass)#40 (2) {
  ["statusCode"]=>
  int(10000)
  ["verifyConfig"]=>
  object(stdClass)#41 (6) {
    ["code"]=>
    int(10000)
    ["type"]=>
    string(6) "verify"
    ["subtype"]=>
    string(5) "slide"
    ["fp"]=>
    string(39) "verify_587663ee6601736902403e9ee6502e0c"
    ["region"]=>
    string(2) "va"
    ["detail"]=>
    string(436) "Y*DfagOJ5fxblqdEF3EaXiR1vu6e5OvIWPCn4wnWJS2B9xD4gb7t-njRTM
sFNNl1KpI2hng*dWBf-pHJDiD5jEeffIykQiAFAarqNBh5cb0h2wGJ02sJhsMjJ0nPSsxvhM9za
TBWiKXaANjkpZINZvFlBRfy5KioxD-dYxXaffe7pCkgNqtEmrlFcSmPnh*t-tbJMpQI4pMltk-1
fy2-O2gyu9T1Ov1sYiDaHKbl*4YeKEEQIGp0Vmmce52ZOSzbOL5Os3sXyrBGkKTtjkKUhjuhTrq
qW1az1EmTik58ScRejApeBXRwBSdRTisdUhd9b9KhnFyMHx13JDuWHUyWQXhnB6Gxin3CXt5h2C
G6LW6Rzz9**B1wW-BZaKgEwD2kXsYv*OsxYGCcsQFavE0-Uk9SKYrBExXykPk-qG6RQK8FEti4Z
g.."
  }
}
`

**Comment by cr1gger** [comment]
> Только что протестировал, похоже, с моей стороны все работает нормально. Попробуйте использовать прокси.

I tried it through a proxy, similarly

**Comment by ssovit** [comment]
try updating the package to the latest. You are on old version of the package.
