### ISSUE TITLE
The PHP script works perfect but the playAddr returned doesn't work.

### ISSUE THREAD

**Issue by merchant-playbook** [ssovit/TikTok-API-PHP#29]
**Describe the bug**
The PHP script works perfect but the playAddr returned doesn't work.

## If fields below is empty then issue will be Ignored and Closed

**To Reproduce**
- PHP Version: PHP Version 7.4.3
- Package Version: 1.3.1
- Used Method: getVideoByID
- Used options: No
- Do you use this package with VPS, VPN or proxy? No
- Can you access TikTok website without captcha or forced login screen? Yes
- Is the profile you are tyring to get data from is private? No
- Preferably provide URL to the profile,hashtag,video and etc page: https://m.tiktok.com/v/6829540826570296577.html

**Screenshots**
![Screen Shot 2021-03-19 at 23 08 54](https://user-images.githubusercontent.com/469150/111809955-17fafb00-8908-11eb-9fac-70ed3e80c72c.png)
![Screen Shot 2021-03-19 at 23 07 54](https://user-images.githubusercontent.com/469150/111809846-fd288680-8907-11eb-8cf0-711bdfc4c0fc.png)

**Comment by ssovit** [comment]
You can't play the video directly in your browser. You need proper cookies and headers. See `example/stream-video.php` which uses `Stream.php` class.

**Comment by ssovit** [comment]
Close this issue if you follow the example.
