### ISSUE TITLE
Internal server error 500 while executing download-video.php

### ISSUE THREAD

**Issue by sir-argupta** [ssovit/TikTok-API-PHP#3]
hey,
i was testing your api on my server, it gives me internal error whenever i run download-video.php. rest of the funtions are working fine. any idea why??

my url is http://argupta.thats.im/api-v1/call/download-video.php

kindly help.

thank you!!

**Comment by ssovit** [comment]
can you dump your error log?

**Comment by sir-argupta** [comment]
error log
020-10-12 01:10:21.805669 [NOTICE] [41887] [49.37.85.86:6598#APVH_www.argupta.thats.im] [STDERR] PHP Fatal error:  Uncaught Error: Class 'Sovit\Tiktok\Download' not found in /home/arguptat/domains/argupta.thats.im/public_html/api-v1/call/download-video.php:5
Stack trace:
#0 {main}
  thrown in /home/arguptat/domains/argupta.thats.im/public_html/api-v1/call/download-video.php on line 5
2020-10-12 01:11:05.743843 [INFO] [41887] [66.45.245.146:35398:HTTP2-1#APVH_www.argupta.thats.im:443] Auto Index is disabled for [/home/arguptat/domains/argupta.thats.im/private_html/], access denied
2020-10-12 01:11:12.655436 [INFO] [41887] [66.45.245.146:35404:HTTP2-1#APVH_www.argupta.thats.im:443] Auto Index is disabled for [/home/arguptat/domains/argupta.thats.im/private_html/], access denied
2020-10-12 01:11:34.941167 [INFO] [41887] [66.45.245.146:35450:HTTP2-1#APVH_www.argupta.thats.im:443] Auto Index is disabled for [/home/arguptat/domains/argupta.thats.im/private_html/], access denied

**Comment by ssovit** [comment]
You haven't included `Download.php` in your file.

**Comment by sir-argupta** [comment]
firstly i run project on my local xampp server on my laptop.. it works fine.. but when i copied them to my server, download-video.php is not working any more. 
please help 
thank you

**Comment by sir-argupta** [comment]
> You haven't included `Download.php` in your file.

bro i have download.php in my file..

**Comment by ssovit** [comment]
You need to fix the autoload path in your server. Make sure you have uploaded all files from vendor folder once you did `composer install`

Check the filenames in your server. Make sure the filename is Capitalized `Download.php`

**Comment by sir-argupta** [comment]
![image](https://user-images.githubusercontent.com/21137415/95708797-cc6a6400-0c7a-11eb-9b24-398d4e35b6ff.png)
![image](https://user-images.githubusercontent.com/21137415/95708836-ef951380-0c7a-11eb-8d0e-df821ac4fd4e.png)

bro i have these files in my server.. i didn't see any difference

**Comment by ssovit** [comment]
contact me on my profile with your ftp detail sovit.tamrakar@gmail.com or add me on skype @wppress so I can have a look

**Comment by sir-argupta** [comment]
bro i send you an email.. please have look

**Comment by ssovit** [comment]
There's a typo on download-video.php

Change \Sovit\Tiktok\Download();` to `\Sovit\TikTok\Download();` on line 5

**Comment by ssovit** [comment]
Also fixed the typo on github repo
