### ISSUE TITLE
getVideoByUrl return failure in Shared Hosting

### ISSUE THREAD

**Issue by moherik** [ssovit/TikTok-API-PHP#32]
**Describe the bug**
Thanks for your API,
The API is run perfectly on my localhost to getting video data, but its result false on my shared hosting
## If fields below is empty then issue will be Ignored and Closed

**To Reproduce**
- PHP Version: 7.4
- Package Version: ^1.3
- Used Method: getVideoByUrl
- Used options: No
- Do you use this package with VPS, VPN or proxy? Yes
- Can you access TikTok website without captcha or forced login screen? Yes
- Is the profile you are tyring to get data from is private? No
- Preferably provide URL to the profile,hashtag,video and etc page: https://www.tiktok.com/@celalaaaaa/video/6940227664812788993?sender_device=pc&sender_web_id=6950949246494443009&is_from_webapp=v1&is_copy_url=0

**Screenshots**
![image](https://user-images.githubusercontent.com/33406986/115181114-6830cd00-a101-11eb-93eb-1f86b05683aa.png)

**Comment by ssovit** [comment]
make sure your proxy config is valid.

try with the proxy you want to use in browser and access https://www.tiktok.com

**Comment by moherik** [comment]
Great, it worked using another proxy, thanks
