### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by john07-max** [ssovit/TikTok-API-PHP#38]
Locally it works perfectly under Windows 10 and XAMP (with and without proxy).

On a free host 000webhost it also works with and without a proxy.

On the other hand, on any other host I have tried (flaunt7, namecheap, smarterasp.net etc ..) the API returns an empty result (with or without proxy)

I bought the recommended proxy, but no results.

**Comment by ssovit** [comment]
Find better proxy

**Comment by Barcelona** [comment]
> I bought the recommended proxy, but no results.

Yeah, It doesn't work perfectly for me either. I just keep refreshing the site till it works. 
Probably there is no better solution.
