### ISSUE TITLE
I am getting false in response.

### ISSUE THREAD

**Issue by ZaheerAbbasAghani** [ssovit/TikTok-API-PHP#39]
Hi there,
          I had installed your API properly and I am getting no error. But when I do ajax call I am getting false in response. Check Below code for clearification. 
          
          
          `if ( defined( 'XMLRPC_REQUEST' ) || defined( 'REST_REQUEST' ) || ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) || 
          wp_doing_ajax() ) {
          @ini_set( 'display_errors', 1 );
          }
          add_action( 'wp_ajax_fetch_tiktok_user', 'fetch_tiktok_user' );
          add_action( 'wp_ajax_nopriv_fetch_tiktok_user', 'fetch_tiktok_user' );
          function fetch_tiktok_user() {
          
          header("Content-Type: application/json");
          include get_stylesheet_directory(). "/inc/vendor/autoload.php";
          $api = new \Sovit\TikTok\Api();
          $result = $api->getUser("@user6147743657838");
          echo json_encode($result, JSON_PRETTY_PRINT);
           wp_die();
           }`

**Comment by ssovit** [comment]
> Hi there,
> I had installed your API properly and I am getting no error. But when I do ajax call I am getting false in response. Check Below code for clearification.
> 
> ```
>       `if ( defined( 'XMLRPC_REQUEST' ) || defined( 'REST_REQUEST' ) || ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) || 
>       wp_doing_ajax() ) {
>       @ini_set( 'display_errors', 1 );
>       }
>       add_action( 'wp_ajax_fetch_tiktok_user', 'fetch_tiktok_user' );
>       add_action( 'wp_ajax_nopriv_fetch_tiktok_user', 'fetch_tiktok_user' );
>       function fetch_tiktok_user() {
>       
>       header("Content-Type: application/json");
>       include get_stylesheet_directory(). "/inc/vendor/autoload.php";
>       $api = new \Sovit\TikTok\Api();
>       $result = $api->getUser("@user6147743657838");
>       echo json_encode($result, JSON_PRETTY_PRINT);
>        wp_die();
>        }`
> ```

Don't use @ in the username. You should do `$result = $api->getUser("user6147743657838");`

Also, make sure you are using proxy.

**Comment by ZaheerAbbasAghani** [comment]
If I don't use @ sign still I am getting **false** in response.
How to use proxy?

**Comment by ssovit** [comment]
> If I don't use @ sign still I am getting **false** in response.
> How to use proxy?

See readme for options.

**Comment by ZaheerAbbasAghani** [comment]
https://drive.google.com/file/d/17s-JB4R0zRaTmZiCZwH0KQlxwJXK84NW/view?usp=sharing

**Comment by ssovit** [comment]
Proxy example.

https://github.com/ssovit/TikTok-API-PHP/blob/master/example/proxy.php

**Comment by ZaheerAbbasAghani** [comment]
"proxy-host" => "p.webshare.io",
    "proxy-port" => "80",
    "proxy-username" => "proxy-username",
    "proxy-password" => "proxy-password"
    
    How I know that what is my sites proxy host,port,username,password?

**Comment by ssovit** [comment]
> "proxy-host" => "p.webshare.io",
> "proxy-port" => "80",
> "proxy-username" => "proxy-username",
> "proxy-password" => "proxy-password"
> 
> ```
> How I know that what is my sites proxy host,port,username,password?
> ```

You need to purchase proxy from proxy provider.

**Comment by ZaheerAbbasAghani** [comment]
The hosting providers such as godadday. Do they offer such a type of proxy to purchase?
