### ISSUE TITLE
Getting False as response since today

### ISSUE THREAD

**Issue by Nicotroll** [ssovit/TikTok-API-PHP#40]
Hi,
I've been using this API for several months without issues, until today where all my requests are answered with "false".
I'm using residential proxies, and tried using 2 other proxy providers just to make sure but still the same issue.

**To Reproduce**
- PHP Version: 7.4
- Package Version: 2.0
- Used Method: getVideoByID, getUserFeed, getUser
- Used options: proxy
- Do you use this package with VPS, VPN or proxy? on a dedicated serv with residential proxies
- Can you access TikTok website without captcha or forced login screen? yes
- Is the profile you are tyring to get data from is private? no

**Comment by hongle** [comment]
I'm using the Webshare proxy as recommended but unable to retrieve any data. I am able to retrieve without the proxy though.  Hopefully we can get this resolved.

**Comment by ssovit** [comment]
proxy issue
