### ISSUE TITLE
getUserFeed() returns a very large `maxCursor` that returns no `items`

### ISSUE THREAD

**Issue by alkarkhi** [ssovit/TikTok-API-PHP#42]
**Describe the bug**
getUserFeed() returns a very large `maxCursor` that returns no `items`. An example is 1637278868000 which, when passed as a parameter, doesn't fetch any `items`

## If fields below is empty then issue will be Ignored and Closed

**To Reproduce**
- PHP Version: 8.0.13
- Package Version: 2.0.0
- Used Method: getUserFeed()
- Used options: getUserFeed("tiktok")
- Do you use this package with VPS, VPN or proxy? proxy
- Can you access TikTok website without captcha or forced login screen? yes
- Is the profile you are tyring to get data from is private? no
- Preferably provide URL to the profile,hashtag,video and etc page: https://www.tiktok.com/@tiktok

The same doesn't happen with other functions. For example I can use `getTrendingFeed()` which returns a `maxCursor` of 1 which fetches results

**Screenshots**

**Comment by ssovit** [comment]
Stale
