### ISSUE TITLE
Return real followers count

### ISSUE THREAD

**Issue by beshoo** [ssovit/TikTok-API-PHP#44]
Dear all, 
I believe all users know about livecounts.io which somehow can return the real count of the followers of an account.
but this API can not return the real followers count, it just returns what is in the JSON

`"authorStats":{"followerCount":19400,"followingCount":2987,"heart":52700,"` whihc is not correct when the followers count pass the 15000.

like in this example. The real follower's count is 19440 but TikTok round the number.

please advice.

**Comment by ssovit** [comment]
livecounts.io is using mobile app api.. and this repo is using web app api. 

Mobile APP api would return actual stats, while web api would return rounded stats count.

**Comment by beshoo** [comment]
@ssovit kindly may you refer me to the Mobile app API endpoint so i can do the same in my application.
Is there any GitHub repo for this?

**Comment by ssovit** [comment]
There seem not to be free tiktok app api access. I can provide you access or source code. Contact me through contact info readme of this repo

**Comment by beshoo** [comment]
I sent you an email!
