### ISSUE TITLE
getVideoByUrl() & getUser() are always false

### ISSUE THREAD

**Issue by alina-ami** [ssovit/TikTok-API-PHP#48]
**Describe the bug**

I use the method getVideoByUrl for almost 6 months and since January 17 it started returning only `false`.
We use the WebShare proxy as suggested.
I did some debugging and I observed that the code fails at the regex part:

In Api.php:488
```
$result = Helper::string_between($result, '{"props":{"initialProps":{', "</script>");
```
And  the page source returned by the curl call does not contain this string anymore.
The same happens for getUser method.

**To Reproduce**
- PHP Version: 7.3
- Package Version:2.0.0
- Used Method: getVideoByUrl
- Used options: with and without proxy
- Do you use this package with VPS, VPN or proxy? Yes, I tried with multiple paid proxies
- Can you access TikTok website without captcha or forced login screen? yes
- Is the profile you are tyring to get data from is private? No
- Preferably provide URL to the profile,hashtag,video and etc page: any page

**Screenshots**
```
$api = new \Sovit\TikTok\Api([ 
"proxy-host" => config('proxy.host'), 
"proxy-port" => config('proxy.port'),  
"proxy-username" => config('proxy.username'), 
"proxy-password" => config('proxy.password')
]);

$result = $api->getUser('moniquedias961'); // returns false
$result = $api->getVideoByUrl('https://www.tiktok.com/@ravmalik/video/7030873814435138821'); // returns false
```

**Comment by arifrohmadi** [comment]
[alina-ami] I got the same problem. how do you solve it?

**Comment by ssovit** [comment]
Re-open if issue still persists

**Comment by a7maadf** [comment]
@ssovit the issue is still there
