### ISSUE TITLE
$api->getNoWatermark

### ISSUE THREAD

**Issue by idebu** [ssovit/TikTok-API-PHP#5]
$api->getNoWatermark("https://www.tiktok.com/@zachking/video/6829303572832750853");

why result returns false?

**Comment by ssovit** [comment]
update your copy of package to tag 1.1.5

The issue has been fixed.

**Comment by franckitho** [comment]
hi
getNoWatermark return false at the moment

i try with this uri : tiktok.com/@ohmygoal/video/6906975178568338690
