### ISSUE TITLE
Get Feed on Challenge and User not working

### ISSUE THREAD

**Issue by Davpyu** [ssovit/TikTok-API-PHP#53]
**Describe the bug**
As a title say, its not working because when i try to access the link, it return 404 on browser

## If fields below is empty then issue will be Ignored and Closed

**To Reproduce**
- PHP Version: 8.0
- Package Version: 2.0.1
- Used Method: getUserFeed and getChallengeFeed
- Used options:
- Do you use this package with VPS, VPN or proxy? yes, im using proxy and VPS too
- Can you access TikTok website without captcha or forced login screen? as for now no, sometimes it popup the captcha first
- Is the profile you are tyring to get data from is private? no
- Preferably provide URL to the profile,hashtag,video and etc page: https://www.tiktok.com/node/video/feed?type=1&secUid=&id=6739672984652940290&count=30&minCursor=0&maxCursor=0&shareUid=&lang=&verifyFp=

**Screenshots**
![Cuplikan layar 2022-06-15 150603](https://user-images.githubusercontent.com/42276243/173777450-6088dffe-968c-4b1e-9feb-c5e35280cf21.png)

**Comment by Davpyu** [comment]
Just a reference on package in another language, they are using different endpoint.
[Tiktok-Api python](https://github.com/davidteather/TikTok-Api/blob/master/TikTokApi/api/user.py#L151)
I've tried to make the same endpoint and parameters but still getting captcha in the way

**Comment by attend-dunce** [comment]
Any news on this?

**Comment by hacknapier** [comment]
TikTok Captcha Solving Service is available here with demo to Login successfully into your TikTok Account.
https://rapidapi.com/flyCaptcha/api/flycaptcha
