### ISSUE TITLE
Get an artist's feed

### ISSUE THREAD

**Issue by likvp** [ssovit/TikTok-API-PHP#6]
[music] => stdClass Object
--
  | (
  | [id] => 6847427631177452294
  | [title] => Zuwu Ждали Лето
  | [playUrl] => https://sf58-sg.tiktokcdn.com/obj/musically-maliva-obj/6847427593394735878.mp3
  | [coverThumb] => https://p16-sign-sg.tiktokcdn.com/musically-maliva-obj/1653893744153605~c5_100x100.jpeg?x-expires=1605636000&x-signature=dPaMwJAsbQqhSVQxf9AOGHTNakY%3D
  | [coverMedium] => https://p16-sign-sg.tiktokcdn.com/musically-maliva-obj/1653893744153605~c5_720x720.jpeg?x-expires=1605636000&x-signature=KQ4kCGGXgvnfHwpMSN58arYZbSc%3D
  | [coverLarge] => https://p16-sign-sg.tiktokcdn.com/musically-maliva-obj/1653893744153605~c5_1080x1080.jpeg?x-expires=1605636000&x-signature=64QpTs4ePrXuVsABAW3O9%2FlW7c4%3D
  | [authorName] => zuwumusic
  | [original] => 1
  | )

How do I get all artist tracks?
Search for this parameter [video] [music] [authorName] => zuwumusic

**Comment by ssovit** [comment]
Feed by music author isn't available with the API.
