### ISSUE TITLE
Views

### ISSUE THREAD

**Issue by canyesilyurt** [ssovit/TikTok-API-PHP#7]
Hello bro, I liked the api document very much. There is a question I am wondering. Can we make a system to increase the number of views on Tiktok?

**Comment by ssovit** [comment]
increasing views/hearts are supported by this API library.

**Comment by canyesilyurt** [comment]
hello, can you give information about its usage?

**Comment by ssovit** [comment]
> hello, can you give information about its usage?

No. You will need to use x gorgon and x khronos headers used in mobile app to do so.

**Comment by canyesilyurt** [comment]
Thank you bro ❤️🇹🇷

**Comment by xgorgon** [comment]
@janyesilyurt I can sell script to generate xgorgon header contact me at xgorgon@protonmail.com or telegram https://t.me/adotdaniel
